### Get request

@urlEP=http://localhost:8000/api/v1/users
GET {{urlEP}}?id=10&name=shikamaru


### Post user request 
POST {{urlEP}}
Content-Type: application/json
Authorization: 205826

{
 "id": "7",
 "fname": "Naruto",
  "lname": "Uzumaki"
}
### UPDATE  user request
PUT {{urlEP}}
Content-Type: application/json
Authorization: 205826

{
  "id": "2",
  "fname": "Sasuke",
  "lname": "Uchiha"
}

### Delete user request
DELETE  {{urlEP}}/20202

# curl -X POST "http://localhost:8000" -H "Content-Type: application/json" -d '{"id": "9","fname":"Obito","lname": "Uchiha"}' 